version: "3"
services:
  hapi-fhir-jpaserver-start:
    build: .
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - "sqlserver"
  sqlserver:
    container_name: "sqlserver"
    image: mcmoe/mssqldocker
    ports:
      - "1444:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Majubersama79."
      MSSQL_DB: "hapi"
      MSSQL_USER: "tujuhsembilan"
      MSSQL_PASSWORD: "Majubersama79."
    volumes:
      - "sqlserverdata:/var/opt/mssql"
volumes:
  sqlserverdata:
